export const majorLanguages = [
    { key: "en", label: "English" },
    { key: "es", label: "Spanish" },
    { key: "fr", label: "French" },
    { key: "de", label: "German" },
    { key: "zh", label: "Mandarin Chinese" },
    { key: "ja", label: "Japanese" },
    { key: "ko", label: "Korean" },
    { key: "ru", label: "Russian" },
    { key: "pt", label: "Portuguese" },
    { key: "ar", label: "Arabic" },
    { key: "hi", label: "Hindi" },
    { key: "bn", label: "Bengali" },
    { key: "id", label: "Indonesian" },
    { key: "tr", label: "Turkish" },
    { key: "vi", label: "Vietnamese" },
    { key: "pl", label: "Polish" },
    { key: "nl", label: "Dutch" },
    { key: "it", label: "Italian" },
    { key: "th", label: "Thai" },
    { key: "sv", label: "Swedish" },
    { key: "da", label: "Danish" },
    { key: "fi", label: "Finnish" },
    { key: "no", label: "Norwegian" },
    { key: "el", label: "Greek" },
    { key: "he", label: "Hebrew" },
    { key: "ro", label: "Romanian" },
    { key: "hu", label: "Hungarian" },
    { key: "cs", label: "Czech" },
    { key: "sk", label: "Slovak" },
    { key: "uk", label: "Ukrainian" },
    { key: "ms", label: "Malay" },
    { key: "tl", label: "Tagalog (Filipino)" },
    { key: "ur", label: "Urdu" },
    { key: "fa", label: "Persian (Farsi)" },
    { key: "sw", label: "Swahili" },
    { key: "ta", label: "Tamil" },
    { key: "te", label: "Telugu" },
    { key: "mr", label: "Marathi" },
    { key: "gu", label: "Gujarati" },
    { key: "kn", label: "Kannada" }
];