name: CI CD PIPELINE

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Setup environment variables
        run: | 
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy

      - name: Deploy to Vercel
        run: npx vercel deploy --yes --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}